### ISSUE TITLE
Error "Error: b must be length 2" when using $worker_detect_exited() and more than one worker was lost

### ISSUE THREAD

**Issue by MartinHanewald** [mrc-ide/rrq#22]
Hi,

I just experienced the above error, when using the heartbeat functionality and more than one worker was lost. Then the function worker_detect_exited() returns the Error message: "b must be length 2".
Best regards,
Martin

**Comment by MartinHanewald** [comment]
Hi, I have already implemented a fix on my fork. If you add me as a contributor I can submit a pull request.
Thank you for your work.
Best regards,
Martin

**Comment by richfitz** [comment]
Thank you for reporting this - I've made your change in #26, along with a test
